### ISSUE TITLE
Cannot find module 'core-js/modules/es7.string.pad-start'

### ISSUE THREAD

**Issue by Frexuz** [IjzerenHein/react-native-bundle-visualizer#1]
> yarn run react-native-bundle-visualizer
```
yarn run v0.23.4

$ "~/www/rn_app/node_modules/.bin/react-native-bundle-visualizer"
module.js:472
    throw err;
    ^

Error: Cannot find module 'core-js/modules/es7.string.pad-start'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kristiangerardsson/www/flately.com/native_app/node_modules/haul/src/cli.js:10:1)
    at Module._compile (module.js:571:32)
    at loader (/Users/kristiangerardsson/www/flately.com/native_app/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/kristiangerardsson/www/flately.com/native_app/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
✨  Done in 1.01s.
```

**Comment by IjzerenHein** [comment]
What version of node are you using?

**Comment by Frexuz** [comment]
v7.10.0, too old?

**Comment by IjzerenHein** [comment]
Not sure, but I think so. It looks like an error in the Haul bundler. What happens if you use node 8?

**Comment by Frexuz** [comment]
Latest node works :) You might wanna add a minimum requirement in the README :) 👍
