### ISSUE TITLE
Running bundle visualizer in Expo project using Expo Router

### ISSUE THREAD

**Issue by RobertPetricevic** [IjzerenHein/react-native-bundle-visualizer#123]
I'm getting the following error when trying to run bundle visualizer:

Error: The resource `/Users/............../expo-router/entry` was not found.

Has anyone run on this issue before?

**Comment by flexbox** [comment]
confirmed here as well

```
❯ npx react-native-bundle-visualizer

Generating bundle...
                Welcome to Metro v0.76.8
              Fast - Scalable - Integrated


Error: The resource `/Users/.../expo-router/entry` was not found.
    at /Users/.../node_modules/metro/src/IncrementalBundler.js:276:24

=== error === Error: Command failed with exit code 1:
```

I think it's the same as https://github.com/IjzerenHein/react-native-bundle-visualizer/issues/93 we need to change the path of the sourcemap somehow

**Comment by mojavad** [comment]
I have a solution to this - will update here briefly.

**Comment by mojavad** [comment]
@flexbox @RobertPetricevic 

1. Run `npx expo export -p web --dump-sourcemap` in your project. This will create a dist directory with your exported project along with the sourcemaps.
2. Run `npx source-map-explorer dist/**/*.js` to get the graphic representation of your sourcemaps.

**Comment by flexbox** [comment]
@mojavad Nice hack! thanks for sharing

**Comment by Victorcassiano** [comment]
**It didn't work very well for me because of react-native-maps**

### RUN:
`npx expo export -p web --dump-sourcemap`

### Error:

`Starting Metro Bundler
Web Bundling failed 16475ms node_modules\expo-router\entry.js (1214 modules)
Web node_modules\expo-router\entry.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1213/1214)Error: Importing native-only module "react-native/Libraries/Utilities/codegenNativeCommands" on web from: D:\Codigos\saude-express\Mobile\node_modules\react-native-maps\src\MapMarkerNativeComponent.ts
Error: Importing native-only module "react-native/Libraries/Utilities/codegenNativeCommands" on web from: D:\Codigos\saude-express\Mobile\node_modules\react-native-maps\src\MapMarkerNativeComponent.ts
    at resolver (D:\Codigos\saude-express\Mobile\node_modules\@expo\cli\src\start\server\metro\withMetroMultiPlatform.ts:585:19)
    at resolveRequest (D:\Codigos\saude-express\Mobile\node_modules\@expo\cli\src\start\server\metro\withMetroResolvers.ts:76:29)
    at firstResolver (D:\Codigos\saude-express\Mobile\node_modules\react-native-css-interop\src\metro\index.ts:257:26)
    at firstResolver (D:\Codigos\saude-express\Mobile\node_modules\@expo\cli\src\start\server\metro\withMetroResolvers.ts:108:16)
    at resolveRequest (D:\Codigos\saude-express\Mobile\node_modules\@expo\cli\src\start\server\metro\withMetroResolvers.ts:137:16)
    at Object.resolve (D:\Codigos\saude-express\Mobile\node_modules\metro-resolver\src\resolve.js:36:12)
    at ModuleResolver.resolveDependency (D:\Codigos\saude-express\Mobile\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:74:31)
    at DependencyGraph.resolveDependency (D:\Codigos\saude-express\Mobile\node_modules\metro\src\node-haste\DependencyGraph.js:248:43)
    at D:\Codigos\saude-express\Mobile\node_modules\metro\src\lib\transformHelpers.js:165:21
    at resolveDependencies (D:\Codigos\saude-express\Mobile\node_modules\metro\src\DeltaBundler\buildSubgraph.js:42:25)`

**Comment by mojavad** [comment]
@Victorcassiano - I'd say my previous advice is pretty out of date now - if you're on Expo SDK 51+, I'd suggest using Expo Atlas - fingers crossed that will work as expected 🤞

**Comment by Victorcassiano** [comment]
> @Victorcassiano - I'd say my previous advice is pretty out of date now - if you're on Expo SDK 51+, I'd suggest using Expo Atlas - fingers crossed that will work as expected 🤞 

I'm using expo 53 but with native files 😅

**Comment by retyui** [comment]
expo support was updated in [4.0.0](https://github.com/callstack/react-native-bundle-visualizer/releases/tag/v4.0.0)
