### ISSUE TITLE
Not working: Getting this error

### ISSUE THREAD

**Issue by tasneembohra** [IjzerenHein/react-native-bundle-visualizer#3]
` Error running haul bundle --config ./node_modules/react-native-bundle-visualizer/src/webpack.haul.js --platform ios`

> TypeError: Invalid Version: 
at new SemVer (/Users/300006350/workspace/rn-batbelt/node_modules/haul/node_modules/semver/semver.js:293:11)
at compare (/Users/300006350/workspace/rn-batbelt/node_modules/haul/node_modules/semver/semver.js:566:10)
at Function.gte (/Users/300006350/workspace/rn-batbelt/node_modules/haul/node_modules/semver/semver.js:615:10)
at getDefaultConfig (/Users/300006350/workspace/rn-batbelt/node_modules/haul/src/utils/makeReactNativeConfig.js:69:24)
at PLATFORMS.map.platform (/Users/300006350/workspace/rn-batbelt/node_modules/haul/src/utils/makeReactNativeConfig.js:215:34)
at Array.map (<anonymous>)
at makeReactNativeConfig (/Users/300006350/workspace/rn-batbelt/node_modules/haul/src/utils/makeReactNativeConfig.js:213:29)
at Object.bundle (/Users/300006350/workspace/rn-batbelt/node_modules/haul/src/commands/bundle.js:29:7)
at run (/Users/300006350/workspace/rn-batbelt/node_modules/haul/src/cliEntry.js:178:19)
at <anonymous>

**Comment by IjzerenHein** [comment]
Wat version of node are you using?

**Comment by TasneemBohra** [comment]
I am using V8.4.0


________________________________

**Comment by IjzerenHein** [comment]
Okay, in that case node isn't the problem.

Could you try things I suggested in my last post in issue #2 ?

**Comment by TasneemBohra** [comment]
okay, 'll check.


________________________________

**Comment by IjzerenHein** [comment]
Hi, I've just released v1.2.0 of react-native-bundle-visualizer, it now works with RN49. Let me know whether that resolves your problem.

**Comment by TasneemBohra** [comment]
Hi , okay. Will check and let you know. Thanks for replying.


________________________________
