### ISSUE TITLE
EXPO SDK 44: error Unable to resolve module ../../App from node_modules/expo/AppEntry.js: 

### ISSUE THREAD

**Issue by hani-q** [IjzerenHein/react-native-bundle-visualizer#74]
Hi,

I keep getting this error when I run it on a EXPO SDK 44 project.

It is a JSX project

```

{
    "main": "node_modules/expo/AppEntry.js",
    "scripts": {
        "start": "expo start",
        "android": "expo start --android",
        "ios": "expo start --ios",
        "web": "expo start --web",
        "postinstall": "rndebugger-open --expo",
        "eject": "expo eject",
        "lint": "eslint --ext .js,.jsx src --color"
    },
    "dependencies": {
        "@expo/vector-icons": "^12.0.0",
        "@react-native-async-storage/async-storage": "~1.15.0",
        "@react-native-community/datetimepicker": "4.0.0",
        "@react-native-community/masked-view": "0.1.10",
        "@react-native-community/netinfo": "7.1.3",
        "@react-native-community/slider": "4.1.12",
        "@sentry/react-native": "^3.2.13",
        "@umalqura/core": "^0.0.7",
        "d3-scale": "1.0.7",
        "date-fns": "^2.11.0",
        "expo": "^44.0.0",
        "expo-app-loading": "~1.3.0",
        "expo-application": "~4.0.1",
        "expo-av": "~10.2.0",
        "expo-camera": "~12.1.0",
        "expo-constants": "~13.0.1",
        "expo-device": "~4.1.0",
        "expo-file-system": "~13.1.2",
        "expo-font": "~10.0.4",
        "expo-image-picker": "~12.0.1",
        "expo-linear-gradient": "~11.0.0",
        "expo-location": "~14.0.1",
        "expo-network": "~4.1.0",
        "expo-notifications": "~0.14.0",
        "expo-splash-screen": "~0.14.1",
        "expo-system-ui": "~1.1.0",
        "expo-updates": "~0.11.6",
        "firebase": "7.9.0",
        "formik": "^1.5.8",
        "lodash": "^4.17.19",
        "moment": "^2.24.0",
        "moment-duration-format": "^2.3.2",
        "react": "17.0.1",
        "react-dom": "17.0.1",
        "react-native": "0.64.3",
        "react-native-bundle-visualizer": "2.3.0",
        "react-native-calendar-heatmap": "^0.2.4",
        "react-native-calendar-strip": "^2.0.9",
        "react-native-chart-kit": "^5.6.1",
        "react-native-country-picker-modal": "^2.0.0",
        "react-native-elements": "^1.2.7",
        "react-native-gesture-handler": "~2.1.0",
        "react-native-gifted-chat": "^0.16.3",
        "react-native-keyboard-aware-scroll-view": "^0.9.1",
        "react-native-paper": "^3.6.0",
        "react-native-popup-menu": "^0.15.9",
        "react-native-reanimated": "~2.3.1",
        "react-native-root-siblings": "^4.0.6",
        "react-native-root-toast": "^3.2.1",
        "react-native-safe-area-context": "3.3.2",
        "react-native-screens": "~3.10.1",
        "react-native-segmented-control-tab": "^3.4.1",
        "react-native-simple-time-picker": "^0.2.0",
        "react-native-step-indicator": "^1.0.3",
        "react-native-svg": "12.1.1",
        "react-native-svg-charts": "^5.4.0",
        "react-native-swipeable-view-wrapper": "^0.1.2",
        "react-native-web": "~0.13.12",
        "react-native-webview": "11.15.0",
        "react-native-x-carousel": "^1.0.1",
        "react-navigation": "^4.4.0",
        "react-navigation-stack": "^2.1.1",
        "react-navigation-tabs": "^2.7.0",
        "react-redux": "^7.2.0",
        "redux": "^4.0.5",
        "redux-devtools-extension": "^2.13.8",
        "redux-persist": "^5.10.0",
        "redux-thunk": "^2.3.0",
        "sentry-expo": "^4.0.0",
        "yup": "^0.28.1"
    },
    "pre-commit": [
        "lint"
    ],
    "devDependencies": {
        "@babel/core": "^7.12.9",
        "babel-eslint": "^10.1.0",
        "babel-preset-expo": "9.0.2",
        "eslint": "^7.5.0",
        "eslint-config-prettier": "^6.10.0",
        "eslint-config-react-app": "^5.2.1",
        "eslint-plugin-flowtype": "^5.2.0",
        "eslint-plugin-import": "^2.22.0",
        "eslint-plugin-jsx-a11y": "^6.3.1",
        "eslint-plugin-prettier": "^3.1.4",
        "eslint-plugin-react": "^7.20.3",
        "eslint-plugin-react-hooks": "^4.0.8",
        "eslint-plugin-react-native": "^3.8.1",
        "pre-commit": "^1.2.2",
        "prettier": "^1.19.1",
        "react-native-debugger-open": "^0.3.24"
    },
    "private": true
}

```

```


q@Hanis-MacBook-Pro kaqa-app % yarn run react-native-bundle-visualizer  --verbose              
yarn run v1.22.17
$ /Users/q/work/code/kaqa-app/node_modules/.bin/react-native-bundle-visualizer --verbose
Generating bundle...
                    Welcome to Metro!
              Fast - Scalable - Integrated


Error: Unable to resolve module ../../App from /Users/q/work/code/kaqa-app/node_modules/expo/AppEntry.js: 

None of these files exist:
  * App(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * App/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  1 | import registerRootComponent from 'expo/build/launch/registerRootComponent';
  2 |
> 3 | import App from '../../App';
    |                  ^
  4 |
  5 | registerRootComponent(App);
  6 |
    at ModuleResolver.resolveDependency (/Users/q/work/code/kaqa-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:211:15)
    at DependencyGraph.resolveDependency (/Users/q/work/code/kaqa-app/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at Object.resolve (/Users/q/work/code/kaqa-app/node_modules/metro/src/lib/transformHelpers.js:317:42)
    at resolve (/Users/q/work/code/kaqa-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)
    at /Users/q/work/code/kaqa-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/q/work/code/kaqa-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)
    at /Users/q/work/code/kaqa-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/q/work/code/kaqa-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)
info Run CLI with --verbose flag for more details.
/Users/q/work/code/kaqa-app/node_modules/react-native-bundle-visualizer/node_modules/execa/lib/error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: ./node_modules/.bin/react-native bundle --platform ios --dev false --entry-file ./node_modules/expo/AppEntry.js --bundle-output /var/folders/nh/nh_n20t92t3529htrfqw2xn80000gn/T/react-native-bundle-visualizer/KaQa/ios.bundle --sourcemap-output /var/folders/nh/nh_n20t92t3529htrfqw2xn80000gn/T/react-native-bundle-visualizer/KaQa/ios.bundle.map
error Unable to resolve module ../../App from /Users/q/work/code/kaqa-app/node_modules/expo/AppEntry.js: 

None of these files exist:
  * App(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * App/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  1 | import registerRootComponent from 'expo/build/launch/registerRootComponent';
  2 |
> 3 | import App from '../../App';
    |                  ^
  4 |
  5 | registerRootComponent(App);
  6 |.
                    Welcome to Metro!
              Fast - Scalable - Integrated


Error: Unable to resolve module ../../App from /Users/q/work/code/kaqa-app/node_modules/expo/AppEntry.js: 

None of these files exist:
  * App(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * App/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  1 | import registerRootComponent from 'expo/build/launch/registerRootComponent';
  2 |
> 3 | import App from '../../App';
    |                  ^
  4 |
  5 | registerRootComponent(App);
  6 |
    at ModuleResolver.resolveDependency (/Users/q/work/code/kaqa-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:211:15)
    at DependencyGraph.resolveDependency (/Users/q/work/code/kaqa-app/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at Object.resolve (/Users/q/work/code/kaqa-app/node_modules/metro/src/lib/transformHelpers.js:317:42)
    at resolve (/Users/q/work/code/kaqa-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)
    at /Users/q/work/code/kaqa-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/q/work/code/kaqa-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)
    at /Users/q/work/code/kaqa-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/q/work/code/kaqa-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)
info Run CLI with --verbose flag for more details.
    at makeError (/Users/q/work/code/kaqa-app/node_modules/react-native-bundle-visualizer/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/q/work/code/kaqa-app/node_modules/react-native-bundle-visualizer/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 1: ./node_modules/.bin/react-native bundle --platform ios --dev false --entry-file ./node_modules/expo/AppEntry.js --bundle-output /var/folders/nh/nh_n20t92t3529htrfqw2xn80000gn/T/react-native-bundle-visualizer/KaQa/ios.bundle --sourcemap-output /var/folders/nh/nh_n20t92t3529htrfqw2xn80000gn/T/react-native-bundle-visualizer/KaQa/ios.bundle.map',
  command: './node_modules/.bin/react-native bundle --platform ios --dev false --entry-file ./node_modules/expo/AppEntry.js --bundle-output /var/folders/nh/nh_n20t92t3529htrfqw2xn80000gn/T/react-native-bundle-visualizer/KaQa/ios.bundle --sourcemap-output /var/folders/nh/nh_n20t92t3529htrfqw2xn80000gn/T/react-native-bundle-visualizer/KaQa/ios.bundle.map',
  escapedCommand: '"./node_modules/.bin/react-native" bundle --platform ios --dev false --entry-file "./node_modules/expo/AppEntry.js" --bundle-output "/var/folders/nh/nh_n20t92t3529htrfqw2xn80000gn/T/react-native-bundle-visualizer/KaQa/ios.bundle" --sourcemap-output "/var/folders/nh/nh_n20t92t3529htrfqw2xn80000gn/T/react-native-bundle-visualizer/KaQa/ios.bundle.map"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '                    Welcome to Metro!\n' +
    '              Fast - Scalable - Integrated\n' +
    '\n' +
    '\n' +
    'Error: Unable to resolve module ../../App from /Users/q/work/code/kaqa-app/node_modules/expo/AppEntry.js: \n' +
    '\n' +
    'None of these files exist:\n' +
    '  * App(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)\n' +
    '  * App/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)\n' +
    "\x1B[0m \x1B[90m 1 |\x1B[39m \x1B[36mimport\x1B[39m registerRootComponent \x1B[36mfrom\x1B[39m \x1B[32m'expo/build/launch/registerRootComponent'\x1B[39m\x1B[33m;\x1B[39m\x1B[0m\n" +
    '\x1B[0m \x1B[90m 2 |\x1B[39m\x1B[0m\n' +
    "\x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 3 |\x1B[39m \x1B[36mimport\x1B[39m \x1B[33mApp\x1B[39m \x1B[36mfrom\x1B[39m \x1B[32m'../../App'\x1B[39m\x1B[33m;\x1B[39m\x1B[0m\n" +
    '\x1B[0m \x1B[90m   |\x1B[39m                  \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 4 |\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 5 |\x1B[39m registerRootComponent(\x1B[33mApp\x1B[39m)\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 6 |\x1B[39m\x1B[0m\n' +
    '    at ModuleResolver.resolveDependency (/Users/q/work/code/kaqa-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:211:15)\n' +
    '    at DependencyGraph.resolveDependency (/Users/q/work/code/kaqa-app/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)\n' +
    '    at Object.resolve (/Users/q/work/code/kaqa-app/node_modules/metro/src/lib/transformHelpers.js:317:42)\n' +
    '    at resolve (/Users/q/work/code/kaqa-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)\n' +
    '    at /Users/q/work/code/kaqa-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26\n' +
    '    at Array.reduce (<anonymous>)\n' +
    '    at resolveDependencies (/Users/q/work/code/kaqa-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)\n' +
    '    at /Users/q/work/code/kaqa-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at asyncGeneratorStep (/Users/q/work/code/kaqa-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)\n' +
    'info Run CLI with --verbose flag for more details.',
  stderr: 'error Unable to resolve module ../../App from /Users/q/work/code/kaqa-app/node_modules/expo/AppEntry.js: \n' +
    '\n' +
    'None of these files exist:\n' +
    '  * App(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)\n' +
    '  * App/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)\n' +
    "\x1B[0m \x1B[90m 1 |\x1B[39m \x1B[36mimport\x1B[39m registerRootComponent \x1B[36mfrom\x1B[39m \x1B[32m'expo/build/launch/registerRootComponent'\x1B[39m\x1B[33m;\x1B[39m\x1B[0m\n" +
    '\x1B[0m \x1B[90m 2 |\x1B[39m\x1B[0m\n' +
    "\x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 3 |\x1B[39m \x1B[36mimport\x1B[39m \x1B[33mApp\x1B[39m \x1B[36mfrom\x1B[39m \x1B[32m'../../App'\x1B[39m\x1B[33m;\x1B[39m\x1B[0m\n" +
    '\x1B[0m \x1B[90m   |\x1B[39m                  \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 4 |\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 5 |\x1B[39m registerRootComponent(\x1B[33mApp\x1B[39m)\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 6 |\x1B[39m\x1B[0m.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by flexbox** [comment]
Hello @hani-q 

Have you tried `expo-atlas` with expo SDK 51?
https://expo.dev/blog/introducing-expo-atlas

If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨

**Comment by retyui** [comment]
expo support was updated in [4.0.0](https://github.com/callstack/react-native-bundle-visualizer/releases/tag/v4.0.0)
